// Mock data for Jonathan Banks' collector homepage

window.CARDSTOCK_DATA = {
  user: {
    name: "Jonathan Banks",
    handle: "jbanks53",
    city: "Vienna, VA",
    team: "Los Angeles Dodgers",
    teamShort: "LAD",
    joined: "Est. 2023",
    players: ["Albert Pujols", "Mike Trout", "Roberto Clemente", "Sandy Koufax", "Ron Cey"],
    bio: "Chasing every Topps set from '53 to '80. Traders welcome. Will travel for a clean '55 Koufax RC.",
  },
  stats: {
    cards: 4281,
    sets: 12,
    trades: 87,
    value: 142340,
    wantlist: 316,
  },
  tabs: ["Home", "Collection", "Want List", "Trades", "Activity"],
  sets: [
    { year: 1953, name: "Topps Baseball", have: 248, total: 274, color: "#b4462b" },
    { year: 1956, name: "Topps Baseball", have: 312, total: 340, color: "#2f4a32" },
    { year: 1962, name: "Topps Baseball", have: 389, total: 598, color: "#1b2a49" },
    { year: 1968, name: "Topps Baseball", have: 501, total: 598, color: "#b8923a" },
    { year: 1971, name: "Topps Baseball", have: 412, total: 752, color: "#1b2a49" },
    { year: 1975, name: "Topps Baseball", have: 602, total: 660, color: "#b4462b" },
    { year: 1978, name: "Topps Baseball", have: 710, total: 726, color: "#2f4a32" },
    { year: 1980, name: "Topps Baseball", have: 495, total: 726, color: "#1b2a49" },
  ],
  favorites: [
    { id: "f1", year: 1955, player: "Sandy Koufax", team: "BKN", set: "Topps", num: "#123", grade: "PSA 5", hero: true, colors: ["#c2342a", "#f4d06f"] },
    { id: "f2", year: 1972, player: "Roberto Clemente", team: "PIT", set: "Topps", num: "#309", grade: "SGC 7", colors: ["#1b2a49", "#d9b668"] },
    { id: "f3", year: 1975, player: "Ron Cey", team: "LAD", set: "Topps", num: "#390", grade: "PSA 8", colors: ["#2f4a32", "#ece0be"] },
    { id: "f4", year: 1954, player: "Ted Williams", team: "BOS", set: "Topps", num: "#1", grade: "PSA 4", colors: ["#b4462b", "#1b2a49"] },
    { id: "f5", year: 2001, player: "Albert Pujols RC", team: "STL", set: "Bowman Chrome", num: "#340", grade: "BGS 9.5", colors: ["#8f331d", "#f3ead3"] },
    { id: "f6", year: 2011, player: "Mike Trout RC", team: "LAA", set: "Topps Update", num: "#US175", grade: "PSA 10", colors: ["#b8923a", "#1b2a49"] },
  ],
  feed: [
    {
      id: "p1",
      kind: "wantlist-hit",
      time: "12 min ago",
      user: { name: "Marcy Fernandez", handle: "mfdiamond", av: "M" },
      card: { year: 1968, player: "Nolan Ryan RC", set: "Topps", num: "#177", grade: "PSA 4", colors: ["#b4462b", "#1b2a49"] },
      price: 2450,
      action: "listed",
      note: "Fresh from PSA. Open to trades for '53 Topps hi-numbers.",
      likes: 24, comments: 6,
    },
    {
      id: "p2",
      kind: "comment",
      time: "1 hr ago",
      user: { name: "Dale Rutherford", handle: "drutherford", av: "D" },
      target: "your 1955 Koufax RC",
      body: "That corner is sharper than any '55 I've seen. What book are you using on this one?",
      likes: 3, comments: 2,
    },
    {
      id: "p3",
      kind: "wantlist-hit",
      time: "3 hr ago",
      user: { name: "Topps Vault", handle: "toppsvault", av: "T", verified: true },
      card: { year: 1953, player: "Satchel Paige", set: "Topps", num: "#220", grade: "SGC 3", colors: ["#2f4a32", "#d9b668"] },
      price: 8900,
      action: "auction",
      auctionEnds: "2d 14h",
      likes: 142, comments: 38,
    },
    {
      id: "p4",
      kind: "post",
      time: "5 hr ago",
      user: { name: "Ellis Park", handle: "ellispk", av: "E" },
      body: "Finally completed the '75 Topps mini set. Eight years. Trading partner shoutout to @jbanks53 who sent me the last three needs.",
      photo: true,
      likes: 89, comments: 17,
    },
    {
      id: "p5",
      kind: "wantlist-hit",
      time: "Yesterday",
      user: { name: "Iris Nakamura", handle: "irisn", av: "I" },
      card: { year: 1962, player: "Maury Wills", set: "Topps", num: "#489", grade: "Raw EX", colors: ["#1b2a49", "#f3ead3"] },
      price: 185,
      action: "listed",
      note: "Centering is off but corners are clean. Priced to move.",
      likes: 11, comments: 3,
    },
  ],
  activity: [
    { id: "a1", text: "Dale commented on your 1955 Koufax", time: "1h", dot: "#b4462b" },
    { id: "a2", text: "3 new want list matches", time: "3h", dot: "#b8923a" },
    { id: "a3", text: "Ellis tagged you in a post", time: "5h", dot: "#2f4a32" },
    { id: "a4", text: "Trade offer from @toppsvault", time: "1d", dot: "#1b2a49" },
    { id: "a5", text: "Marcy liked your 1972 Clemente", time: "2d", dot: "#b4462b" },
  ],
};
